services:

  frontend:
    build:
      context: ./frontend
    restart: always
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./frontend/application:/home/node/app
      - ./.env:/home/node/app/.env
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: ${NODE_ENV}
      NPM_CONFIG_LOGLEVEL: info
    command: ["bash", "-lc", "pnpm install && pnpm dev --host 0.0.0.0"]

  ws:
    build:
      context: ./ws
    restart: always
    user: "node"
    working_dir: /home/node/app
    ports:
      - "3000:3000"
    volumes:
      - ./ws/application:/home/node/app
      - ./.env:/home/node/app/.env
    environment:
      NODE_ENV: ${NODE_ENV}
      NPM_CONFIG_LOGLEVEL: info
    command: ["pnpm", "dev"]

  database:
    image: mysql:8.1.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    volumes:
      - database_volume:/var/lib/mysql

volumes:
  database_volume:
